Modified boxes_to_shapefile function
weecology/DeepForest pull request #597
Opened 2024-01-14 16:47 UTC by Om-Doiphode

Fixes Issue #516: 

The following modifications have been made:

- Updated the `boxes_to_shapefile` function in `utilities.py` to use the 'rgb' argument instead of 'image_path'.
- Modified the test functions in `test_utilities.py` to ensure the correct functionality of the modified `boxes_to_shapefile` function.

2024-04-01 17:50 UTC, bw4sz commented
We just need to update docs and examples to match. Quick search found 

https://deepforest.readthedocs.io/en/latest/annotation.html#how-can-i-view-current-predictions-as-shapefiles

2024-04-02 00:34 UTC, ethanwhite commented
I like this change, but note that it is backwards breaking (including for some of the lab's code). Ideally once we merge this the next release should be 2.0. A couple of possible ways to avoid needing to do this:

1. One option when deprecating positional args is to replace the function with one with a new name and then deprecate the old function. This might actually be the best solution here since then we wouldn't be rushed into 2.0. Possible names include `reproject_boxes`, `boxes_to_projection`, `boxes_to_original_projection`.
2. This also relates to #638 and #608. So one option is to move the officially supported behavior to inside the relevant functions with an option argument to maintain projection when present. We then deprecate the function instructing the user to use the optional argument to the relevant function (and since this is now internal we avoid  future issues with user facing changes).
3. If (1) and (2) don't work for some reason then we could at least check the new `rgb` argument to see if it includes a filename. If it doesn't then perform the previous behavior and throw a deprecation warning. This would at least prevent breaking code where `root_dir` was used positionally.

Thoughts?

2024-04-02 00:34 UTC, ethanwhite requested changes
See my comment about backwards compatibility and alternative approaches before merging this.

2024-04-28 14:01 UTC, ethanwhite commented
@bw4sz - can you response to https://github.com/weecology/DeepForest/pull/597#issuecomment-2030852489 when you have a minute so that we can get this one moving forward

2024-05-13 17:01 UTC, bw4sz commented
I don't think we are ready for this change. There is a geo-type branch that will hold points, polygons, and boxes as part of geodataframe objects. We should wait until I finish that branch this summer.

2024-05-15 14:27 UTC, ethanwhite commented
OK. Thanks @bw4sz. Given that I'm going to close this PR and I've assigned #516 to you so that folks know not to work on it further until you say so. I'm going to move the text of my comment over there.

2024-05-15 14:27 UTC, closed without merging

2024-05-15 14:27 UTC, ethanwhite commented
Thanks for the contribution @Om-Doiphode - we just weren't quite ready for this one yet. Once @bw4sz lets us know this is ready to proceed we can chat about coming back to it.