Updated ConfigurationFile.md file
weecology/DeepForest pull request #623
Opened 2024-03-19 14:30 UTC by Om-Doiphode

Fixes issue #613

2024-03-20 16:54 UTC, henrykironde requested changes

2024-03-20 16:54 UTC, henrykironde commented on docs/ConfigurationFile.md
>  Deepforest comes with a sample config file, deepforest_config.yml. Edit this file to change settings while developing models. Please note that if you would like for deepforest to save the config file
@Om-Doiphode thank you for this Pr, let's add those details in line 5.  Something like:

DeepForest includes a default sample config file named deepforest_config.yml. Users have the option to override this file by creating their own custom config file. Initially, DeepForest scans the current working directory for the file. If it's not found there, it automatically resorts to using the default configuration.

You can edit this file to adjust settings while developing models. Please note that if you wish for DeepForest to save the config file upon reload (using deepforest.save_model),

2024-03-20 17:27 UTC, henrykironde approved these changes
LGTM

2024-03-21 12:47 UTC, ethanwhite commented
Thanks @Om-Doiphode!

2024-03-21 12:47 UTC, merged