solve docstring formatting issue
weecology/DeepForest pull request #714
Opened 2024-07-09 15:50 UTC by Mu-Magdy

As mentioned in #690 
The docstring formatting was bad and missing carriage return. 

- Checked All the docstrings
- Added carriage return
- Built the docs and validated the formatting is good

2024-07-09 15:51 UTC, Mu-Magdy commented
closes #690

2024-07-16 00:27 UTC, henrykironde requested changes
The PR looks good, We are going to add some doctoring checks in the Ci/CD pipeline

2024-07-18 19:27 UTC, henrykironde approved these changes

2024-07-18 19:29 UTC, merged

2024-07-18 19:30 UTC, henrykironde commented
Thanks @Mu-Magdy for these changes. They are good.