Added nesting of sidebar items
weecology/DeepForest pull request #752
Opened 2024-08-16 13:51 UTC by Om-Doiphode

Fixes issue #713 

- Changed the documentation theme from `furo` to `pydata-sphinx-theme`
-  Implemented nesting of menus and submenus in the `Section Navigation`.
- Improved the overall structure and navigation of the documentation.
- Ensured that all relevant sections are properly organized under their respective categories.

2024-08-18 03:20 UTC, henrykironde requested changes
@Om-Doiphode, thank you for these changes. The documentation updates align well with what we discussed. However, I have a few suggestions:

It's standard practice to keep the `source` or `api` directories dedicated solely to API module documentation. This helps streamline maintenance when the source code is updated. The `conf.py` file should remain in the default location: `docs/conf.py`. I don't think we need the `deepforest_docs` folder. We can remove it, and all the subdirectories can be moved directly under `docs/`.

We still have some redundant  parts like getting started appear twice, in the[ introduction]( https://deepforest--752.org.readthedocs.build/en/752/deepforest_docs/introduction/getting_started.html#) and again as a [main topic](https://deepforest--752.org.readthedocs.build/en/752/deepforest_docs/getting_started/index.html).

2024-08-18 05:05 UTC, henrykironde commented
Can you rebase with main

2024-08-18 05:24 UTC, henrykironde commented
Make this one commit. Amend the commits to one

2024-08-19 21:26 UTC, bw4sz commented
@Om-Doiphode Once you rebase, i'm excited to get this merged. Let us know if you need help.

2024-08-20 03:22 UTC, henrykironde requested changes
Make one commit. 
Make sure the tests pass. Look at the error message and see if you can figure out the reason why it is failing.

2024-08-20 03:22 UTC, henrykironde commented on dev_requirements.txt
> +docutils<0.18
remove this dep, "docutils<0.18"

2024-08-20 06:32 UTC, henrykironde commented
@Om-Doiphode Use `pytest --nbmake docs/**/*_test.ipynb` to test specific notebooks. To exclude certain notebooks from CI/CD runs, ensure the ones you want to test end with `_test.ipynb`. This approach avoids running time-consuming notebooks that should be tested locally. Make sure when you run  `ls docs/**/*_test.ipynb` locally, you retriever the files expected to be tested.

2024-08-21 22:41 UTC, bw4sz commented
@Om-Doiphode, rebase, there was another PR.

2024-09-10 21:21 UTC, closed without merging