Batch Predicitions
weecology/DeepForest pull request #856
Opened 2024-12-14 02:47 UTC by RohitP2005

I added a batch function mirroring the functionalities of predict_image,predict_tile and predict_file. I documented this behaviour inside a file called batch_predicitions.md since i was unsure where to document those. I also added test cases for the batch function, but commented them in the last of the file. Waiting for any corrections needed

2024-12-17 23:27 UTC, bw4sz commented
@RohitP2005 , you just have a really small error on the readthedocs index, not in the source code.

2024-12-17 23:29 UTC, bw4sz commented
closes #849 when we finish this and merge.

2024-12-18 03:47 UTC, RohitP2005 commented
@bw4sz  yeah okay , thanks for the clarrifications. I will look into it

2024-12-19 13:16 UTC, RohitP2005 commented
I made the necessary changes in the latest commit, Can my pull request be merged

2025-01-04 15:42 UTC, bw4sz requested changes
I left a few comments and questions, but the core case here is good, thanks for your support and time!

2025-01-04 15:42 UTC, bw4sz commented on src/deepforest/main.py
> +        #convert predictions to dataframes
this looks good, this is the core PR.

2025-01-04 15:42 UTC, bw4sz commented on tests/test_main.py
> +#     Test model's ability to handle large batch sizes.
probably can remove this, this feels like copilot written, needed?

2025-01-04 15:42 UTC, bw4sz commented on tests/test_main.py
> +#         prediction = m.predict_batch(batch)
good, thanks for writing tests.

2025-01-04 16:51 UTC, RohitP2005 commented on tests/test_main.py
> +#     Test model's ability to handle large batch sizes.
okay will remove this

2025-01-04 19:36 UTC, RohitP2005 commented on .pre-commit-config.yaml
> +        stages: [pre-commit]
This makes sure that the hooks are run before the staged chagnes are commited to the respective branches

2025-01-06 22:22 UTC, bw4sz commented
The error 
```
/home/runner/work/DeepForest/DeepForest/docs/user_guide/batch_predicitons.md:document isn't included in any toctree
```

can be solved by removing that file. I am adding a new 'prediction' page to the user guide that will cover this and the other methods. Once that is removed, the tests should pass and we can merge.

2025-01-07 03:08 UTC, RohitP2005 commented
> The error
> 
> ```
> /home/runner/work/DeepForest/DeepForest/docs/user_guide/batch_predicitons.md:document isn't included in any toctree
> ```
> 
> can be solved by removing that file. I am adding a new 'prediction' page to the user guide that will cover this and the other methods. Once that is removed, the tests should pass and we can merge.

Thnks for the classifications @bw4sz .
I will remove the file asap.

2025-01-07 17:43 UTC, bw4sz approved these changes
Thanks for this.

2025-01-07 17:44 UTC, merged

2025-01-07 17:58 UTC, RohitP2005 commented
Anytime @bw4sz